# Takes a file from a repository that initiated a dispatch, processes it, and adds it to this repository

name: CI

on:
  repository_dispatch:
    types: [update-doc]

jobs:
  update-doc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run a multi-line script
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        repo=${{ github.event.client_payload.repo }}
        ref=$(echo ${{github.event.client_payload.ref}} | cut -d/ -f3) # base ref is in the format refs/head/branch
        content=${{ github.event.client_payload.content }}
        echo "Repository: $repo"
        echo "Ref: $ref"
        echo "Content: $content"
        repo_name=$(echo $repo | cut -d/ -f2 | tr '[:upper:]' '[:lower:]')
        echo "Output File: $repo_name".md
        url=$(echo "https://raw.githubusercontent.com/$repo/$ref/$content")
        echo "Fetching content from $url"
        git pull --ff-only # there may be concurrent commits while this job runs
        curl "$url" |  sed -e 's/<!--{//g' -e 's/}-->//g' > "$repo_name".md
        git add .
        git commit -m "Update documentation for ${{ github.event.client_payload.repo }}"
        git push
