name: CI
on:
  push:
    branches: [ master ]

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: Pyrofab/github-actions-test
        event-type: update-doc
        client-payload: '{"repo": "${{ github.repository }}", "ref": "${{ github.ref }}", "content": "README.md"}'
